name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore projects
        run: |
          dotnet restore confole
          dotnet restore confole.sharp

      - name: Build projects
        run: |
          dotnet build confole --no-restore --configuration Release
          dotnet build confole.sharp --no-restore --configuration Release

      - name: Pack projects
        run: |
          dotnet pack confole --no-build --configuration Release --output ./nupkg
          dotnet pack confole.sharp --no-build --configuration Release --output ./nupkg

      - name: Publish packs
        run: dotnet nuget push "nupkg/*.nupkg" --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key "${{ secrets.GITHUB_TOKEN }}"
